---
swagger: '2.0'
info:
    version: 0.1.0
    title: Stock price grabber
definitions:
    stockprice:
        type: object
        properties:
            date:
                type: string
                description: the date of the prices
                example: 2020-04-28
            open:
                type: number
                format: float
                description: opening price
                example: 15.09
            high:
                type: number
                format: float
                description: highest price of the day
                example: 16.12
            low:
                type: number
                format: float
                description: lowest price of the day
                example: 15.01
            close:
                type: number
                format: float
                description: closing price
                example: 15.78
            volume:
                type: integer
                format: int64
                description: traded volume
                example: 83497533
paths:
    /stockprices:
        get:
            produces:
                - application/json
            parameters: []
            operationId: stockprices
            responses:
                200:
                    description: return certain history prices and the average closing prices for a certain stock.
                    schema:
                        type: object
                        description: the stock prices
                        required:
                            - history
                            - average
                            - symbol
                        properties:
                            symbol:
                                type: string
                                description: the stock symbol
                                example: QQQ
                            average:
                                type: number
                                format: float
                                description: average closing price of the past N days
                                example: 15.56
                            history:
                                type: array
                                description: the history prices
                                items:
                                    "$ref": "#/definitions/stockprice"


