// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// StockpricesOKCode is the HTTP code returned for type StockpricesOK
const StockpricesOKCode int = 200

/*StockpricesOK return certain history prices and the average closing prices for a certain stock.

swagger:response stockpricesOK
*/
type StockpricesOK struct {

	/*
	  In: Body
	*/
	Payload *StockpricesOKBody `json:"body,omitempty"`
}

// NewStockpricesOK creates StockpricesOK with default headers values
func NewStockpricesOK() *StockpricesOK {

	return &StockpricesOK{}
}

// WithPayload adds the payload to the stockprices o k response
func (o *StockpricesOK) WithPayload(payload *StockpricesOKBody) *StockpricesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stockprices o k response
func (o *StockpricesOK) SetPayload(payload *StockpricesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StockpricesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
