// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Stockprice stockprice
//
// swagger:model stockprice
type Stockprice struct {

	// closing price
	// Example: 15.78
	Close float32 `json:"close,omitempty"`

	// the date of the prices
	// Example: 2020-04-28
	Date string `json:"date,omitempty"`

	// highest price of the day
	// Example: 16.12
	High float32 `json:"high,omitempty"`

	// lowest price of the day
	// Example: 15.01
	Low float32 `json:"low,omitempty"`

	// opening price
	// Example: 15.09
	Open float32 `json:"open,omitempty"`

	// traded volume
	// Example: 83497533
	Volume int64 `json:"volume,omitempty"`
}

// Validate validates this stockprice
func (m *Stockprice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stockprice based on context it is used
func (m *Stockprice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stockprice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stockprice) UnmarshalBinary(b []byte) error {
	var res Stockprice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
